# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Rohan J Billava\Desktop\finalyearproject\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProjectUI(object):
    def setupUi(self, ProjectUI):
        ProjectUI.setObjectName("ProjectUI")
        ProjectUI.resize(794, 570)
        self.centralwidget = QtWidgets.QWidget(ProjectUI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 791, 571))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/JxUA.gif"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 351, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(254, 255, 189);")
        self.label_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 170, 331, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setMouseTracking(False)
        self.pushButton.setStyleSheet("color: rgb(255, 255, 196);\n"
"border-color: rgb(88, 255, 250);\n"
"background-color: transparent;\n"
"border-width:15px;\n"
"border-style:outset;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 250, 331, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setMouseTracking(False)
        self.pushButton_2.setStyleSheet("color: rgb(255, 255, 196);\n"
"border-color: rgb(88, 255, 250);\n"
"background-color: transparent;\n"
"border-width:15px;\n"
"border-style:outset;\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 350, 131, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setMouseTracking(False)
        self.pushButton_3.setStyleSheet("color: rgb(255, 255, 196);\n"
"border-color: rgb(88, 255, 250);\n"
"background-color: transparent;\n"
"border-width:15px;\n"
"border-style:outset;\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(150, 350, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setMouseTracking(False)
        self.pushButton_4.setStyleSheet("color: rgb(255, 255, 196);\n"
"border-color: rgb(88, 255, 250);\n"
"background-color: transparent;\n"
"border-width:15px;\n"
"border-style:outset;\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        ProjectUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(ProjectUI)
        QtCore.QMetaObject.connectSlotsByName(ProjectUI)

    def retranslateUi(self, ProjectUI):
        _translate = QtCore.QCoreApplication.translate
        ProjectUI.setWindowTitle(_translate("ProjectUI", "MainWindow"))
        self.label_2.setText(_translate("ProjectUI", "WELCOME"))
        self.pushButton.setText(_translate("ProjectUI", "GESTURE BASED INTERACTION"))
        self.pushButton_2.setText(_translate("ProjectUI", "AI VIRTUAL MOUSE"))
        self.pushButton_3.setText(_translate("ProjectUI", "STOP"))
        self.pushButton_4.setText(_translate("ProjectUI", "How To Use?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProjectUI = QtWidgets.QMainWindow()
    ui = Ui_ProjectUI()
    ui.setupUi(ProjectUI)
    ProjectUI.show()
    sys.exit(app.exec_())
